Repository EthicalML/vulkan-kompute, pull requests merged in 2021-01, with the labels that each got.

#108 Fixes for the c++ Simple and Extended examples in readme
  README.md
Labels: documentation

#109 Faster set_data()
  python/src/main.cpp
Labels: enhancement, sig/python

#115 Ubuntu CI
  .github/workflows/cpp_ubuntu.yml
Labels: enhancement

#119 Added further tests to CI and provide Dockerimage with builds to swiftshader
  .dockerignore
  .github/workflows/cpp_tests.yml
  .github/workflows/cpp_ubuntu.yml
  .github/workflows/python_tests.yml
  .gitignore
  Makefile
  README.md
  docker-builders/KomputeBuilder.Dockerfile
  docker-builders/Makefile
  docker-builders/Swiftshader.Dockerfile
  docker-builders/VulkanSDK.Dockerfile
  docs/images/kompute-cpp-video.png
  docs/images/kompute-python-video.png
  docs/index.rst
  docs/overview/build-system.rst
  docs/overview/ci-tests.rst
  python/test/requirements-dev.txt
  setup.py
  test/TestLogisticRegression.cpp
  test/shaders/glsl/test_op_custom_shader.comp
Labels: enhancement

#129 Disallowing zero sized tensors
  src/Tensor.cpp
  src/include/kompute/Tensor.hpp
  test/TestOpTensorCreate.cpp
Labels: bug, enhancement
